case $- in
	*i*) ;;
	*) return ;; 
esac

if [ -d "$HOME/.bin" ]; then
	export PATH="$HOME/.bin:$PATH"
fi

if command -v dircolors &> /dev/null; then
	eval "$(dircolors)"
fi

if pgrep pigpiod &> /dev/null; then
	export GPIOZERO_PIN_FACTORY=pigpio
fi

if command -v starship &> /dev/null; then
	eval "$(starship init bash)"
else
	export PS1="\w \$ "
fi

if command -v vim &> /dev/null; then
	export EDITOR=vim
fi

alias grep="grep --color=auto"
alias ls="ls --color=auto"
alias sudo="sudo "

shopt -s autocd
shopt -s cdspell
shopt -s globstar
shopt -s histappend

