LED_PIN = 4

SENSOR_ECHO_PIN = 15
SENSOR_TRIGGER_PIN = 14
SENSOR_RIGHT_ECHO_PIN = 26
SENSOR_LEFT_ECHO_PIN = 20
SENSOR_RIGHT_TRIGGER_PIN = 17
SENSOR_LEFT_TRIGGER_PIN = 21

LEFT_ENCODER_A_PIN = 27
LEFT_ENCODER_B_PIN = 22
LEFT_MOTOR_DIRECTION_PIN = 6
LEFT_MOTOR_SPEED_PIN = 12

RIGHT_ENCODER_A_PIN = 9
RIGHT_ENCODER_B_PIN = 11
RIGHT_MOTOR_DIRECTION_PIN = 16
RIGHT_MOTOR_SPEED_PIN = 19
