ENCODER_RESOLUTION = 32
GEAR_RATIO = 344.2

WHEEL_TO_MOTOR_RATIO = ENCODER_RESOLUTION * GEAR_RATIO
MOTOR_TO_WHEEL_RATIO = 1 / WHEEL_TO_MOTOR_RATIO

WHEEL_DIAMETER = 54
WHEEL_RADIUS = WHEEL_DIAMETER / 2
WHEEL_SEPARATION = 92
